### ISSUE TITLE
Split the project

### ISSUE THREAD

**Issue by DamienCassou** [bahmutov/cypress-vue-unit-test#380]
Currently, the project consists of files for 2 very different _roles_:

1. a Cypress plugin;
2. examples on how to use the plugin.

By putting the 2 roles together, the reader has a hard time understanding which file belongs to which role:

1. I'm interested in creating a plugin for Cypress to test my own JS component framework and I would like to have an example of another plugin to help me get started;
2. I'm interested in writing tests for my vue component and I would like to have a list of tests for existing vue components.

I think the project would benefit from being split.

**Comment by bahmutov** [comment]
@DamienCassou I am not sure I understand the problem

- the source code for the plugin is here, yes in the `src` folder
- there are lots of examples in `cypress/component` folder, otherwise, how would you know if the plugin even works? How would you know what it can do?

I did expand the "Development" section of the README, hope it makes the code organization a little bit clearer.
